export default {
  main: "/main",
  object_workers_list: "/objectworkerslist",
  journal_lists: "/journallists",
  supervision_journal: "/supervisionjournal",
  building_objects: "/buildingobjects",
  markings_short_names: "/markingsshortnames",
  discipline_short_names: "/disciplineshortnames",
  srd_by_block: "/srdbyblock",
  srd_marking: "/srdmarking",
  work_types: "/worktypes",
  doc_types: "/doctypes",
  retreats_importance: "/retreatsimportance",
  itd_registry: "/itdregistry",
  solutions_registry: "/solutionsregistry",
  author_review_specs: "/authorreviewspecs",
  reg_visit_list: "/regvisitlist",
  organisations: "/organisations",
  consultations: "/consultations",
  auth: "/",
  notFound: "/404",
};